server:
  port: 5555

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MSDH233/microservice_config.git
          username: 853804270@qq.com
          password: Fja9636307
          search-paths: /**
      label: master

eureka:
  client:
      service-url:
        defaultZone: http://eureka7777.com:7777/eureka/,http://eureka7779.com:7779/eureka/,http://eureka7778.com:7778/eureka/


