eureka:
  client:
      service-url:
        defaultZone: http://eureka7777.com:7777/eureka/,http://eureka7779.com:7779/eureka/,http://eureka7778.com:7778/eureka/

spring:
  application:
    name: microservice-zull

server:
  port: 7111
zuul:
  routes:
    api-a:
     path: /api-provider/**
     service-id: microservice-provider
    api-b:
     path: /api-consumer/**
     service-id: microservice-consumer
  host:
    max-total-connections: 500
  ignored-services: "*"